#!/usr/bin/env python3
"""
Collatz Sequence Data Plotter

Reads CSV data generated by collatz_data_generator.cpp and creates a plot.
Requires: matplotlib and pandas

Install: pip install matplotlib pandas
Run: python3 plot_collatz.py
"""

import pandas as pd
import matplotlib.pyplot as plt
import sys

def plot_collatz_data(filename='collatz_data.csv'):
    """Read and plot Collatz sequence max values."""

    try:
        # Read CSV file
        data = pd.read_csv(filename)

        # Create figure
        plt.figure(figsize=(12, 6))

        # Plot the data
        plt.plot(data['index'], data['max_value'], 'b-', linewidth=1, alpha=0.7)
        plt.scatter(data['index'], data['max_value'], c='red', s=10, alpha=0.5)

        # Labels and title
        plt.xlabel('Iteration Index', fontsize=12)
        plt.ylabel('Maximum Value in Sequence', fontsize=12)
        plt.title('Collatz (3n+1)+1 Sequence - Maximum Values', fontsize=14, fontweight='bold')

        # Grid
        plt.grid(True, alpha=0.3)

        # Use logarithmic scale if values span multiple orders of magnitude
        if data['max_value'].max() / data['max_value'].min() > 100:
            plt.yscale('log')
            plt.ylabel('Maximum Value in Sequence (log scale)', fontsize=12)

        # Tight layout
        plt.tight_layout()

        # Show plot
        plt.show()

        # Print statistics
        print("\n" + "="*50)
        print("Statistics:")
        print("="*50)
        print(f"Total iterations: {len(data)}")
        print(f"Min max value: {data['max_value'].min()}")
        print(f"Max max value: {data['max_value'].max()}")
        print(f"Mean max value: {data['max_value'].mean():.2f}")
        print(f"Median max value: {data['max_value'].median():.2f}")
        print("="*50)

    except FileNotFoundError:
        print(f"Error: File '{filename}' not found!")
        print("Please run collatz_data_generator first to generate the data.")
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)

if __name__ == "__main__":
    # Check if custom filename provided
    if len(sys.argv) > 1:
        filename = sys.argv[1]
    else:
        filename = 'collatz_data.csv'

    print(f"Loading data from: {filename}")
    plot_collatz_data(filename)
